### ISSUE TITLE
Simulator cog spams "IndexError: list index out of range" over and over wihin the output channel

### ISSUE THREAD

**Issue by RecklessJames** [hollowstrawberry/crab-cogs#24]
Decided to try out this cog since other past markov related cogs I've used have all been discontinued and/or broke or they always had something wrong with them.

I set up the inputchannels, inputrole, etc, but now it keeps spamming "IndexError: list index out of range" which I am assuming is its attempt at posting comments and convos.

Within the bot console window, it mentions "OperationalError: no such table: messages"

**Comment by RecklessJames** [comment]
Of course the very moment I post this, someone else realized what was wrong. I had to disable it for a time, allow people to post messages, and then turn it back on and it works. So everything is fine, nevermind!

**Comment by hollowstrawberry** [comment]
Glad you found the solution. Thank you for taking an interest in my cog!

I should probably add a check for when the simulator is empty.
