### ISSUE TITLE
If I delete an image from thread, imagelog doesn't seem to work.

### ISSUE THREAD

**Issue by ocformula** [hollowstrawberry/crab-cogs#26]
If I delete an image from thread, imagelog doesn't seem to work.
The logs you'll see at this point are shown below.

> 
>  9월 22 21:14:22 clr-live.lan python[965]: [2023-09-22 21:14:22] [ERROR] discord.client: Ignoring exception in on_raw_message_delete
>  9월 22 21:14:22 clr-live.lan python[965]: Traceback (most recent call last):
>  9월 22 21:14:22 clr-live.lan python[965]:   File "/home/ocformula/redenv/lib/python3.11/site-packages/discord/client.py", line 441, in _run_event
>  9월 22 21:14:22 clr-live.lan python[965]:     await coro(*args, **kwargs)
>  9월 22 21:14:22 clr-live.lan python[965]:   File "/home/ocformula/.local/share/Red-DiscordBot/data/ocformula/cogs/CogManager/cogs/imagelog/imagelog.py", line 46, i>
>  9월 22 21:14:22 clr-live.lan python[965]:     embed.add_field(name=f"Channel", value=channel.mention)
>  9월 22 21:14:22 clr-live.lan python[965]:                                            ^^^^^^^^^^^^^^^
>  9월 22 21:14:22 clr-live.lan python[965]: AttributeError: 'NoneType' object has no attribute 'mention'
>

**Comment by hollowstrawberry** [comment]
That's a strange error, the delete event should carry the information of the current channel and the bot should grab i that channel from cache. However for you it appears as though the channel didn't exist. 

Have you tried deleting an image from a different channel, and/or restarting your bot?
