### ISSUE TITLE
EasyTranslate cog fails to load

### ISSUE THREAD

**Issue by cens0r3d** [hollowstrawberry/crab-cogs#32]
![f46vD2W5Dz](https://github.com/hollowstrawberry/crab-cogs/assets/93801340/48ff3058-d525-41ad-bb2d-c8f2047603a0)

**Comment by hollowstrawberry** [comment]
I updated the cog to change the dependency from googletrans to googletrans-py. This fixes a sporadic issue with old package versions.

1. Uninstall the easytranslate cog
2. Update the crab-cogs repo
3. In the command line, activate your bot's venv then do `pip uninstall googletrans`
4. Restart the bot and install the cog again
