### ISSUE TITLE
UNIQUE constraint failed: messages.id when feeding

### ISSUE THREAD

**Issue by PCJones** [hollowstrawberry/crab-cogs#37]
Hi,

I tried to setup the Simulator cog on my server but when executing !sim feed 1 I get this error:
IntegrityError
UNIQUE constraint failed: messages.id
🧠 Model Built
Analyzed 0 messages

These are my settings
![grafik](https://github.com/hollowstrawberry/crab-cogs/assets/377223/b917e390-fc40-4a59-84a4-b49f5004a1a2)

Thanks for any help :)

**Comment by hollowstrawberry** [comment]
This seems to imply there are two messages with the same ID, which should be impossible. I don't know what could cause something like that...

**Comment by PCJones** [comment]
I don't know for sure but what probably happened was that I added the same #channel twice. It's working now, thanks for the fast response!
